
---
spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false